export const initialStateMotors = {
  location: 0,
  status: "", //using
  gearBox: "",
  engineCapacity: "",
  madeAt: "",
  carBrand: [],
  carModel: [],
  shapeType: [],
  fuelType: [],
  price: [],
  km: [],
  sort: {},
};

// areaFrom: 0,
// areaTo: 0,
// finishedOption: null,
// paymentType: "",
// propFinancing: "",
// searchKeyword: "",
// openFilter: false,
// clickOnUnits: false,
// endPrice: 0,
// sending: false,
// filterResult: null,
// errorResult: null,
// queryInput: {},
// pagesInput: {},
// confirmSendMessage: false,
// messageData: "",
// isSaved: false,
// sortKey: "",
// paymentTypeKey: "",
// finishedOptionKey: "",
// unitTypesKey: "",
// saleOptionKey: "",
// categoryTypeKey: "",
