export const initialStateMotors = {
  status: "",
  gearBox: "",
  engineCapacity: "",
  carBrand: [],
  carModel: [],
  shapeType: [],
  fuelType: [],
  price: [],
  km: [],
  madeAt: "",
  sort: {},
  location: 0,

  // areaFrom: 0,
  // areaTo: 0,
  // finishedOption: null,
  // paymentType: "",
  // propFinancing: "",
  // searchKeyword: "",
  // openFilter: false,
  // clickOnUnits: false,
  // endPrice: 0,
  // sending: false,
  // filterResult: null,
  // errorResult: null,
  // queryInput: {},
  // pagesInput: {},
  // confirmSendMessage: false,
  // messageData: "",
  // isSaved: false,
  // sortKey: "",
  // paymentTypeKey: "",
  // finishedOptionKey: "",
  // unitTypesKey: "",
  // saleOptionKey: "",
  // categoryTypeKey: "",
};
