export const initialStateCategory = {
  pageNumber: 0,
  categoryType: null,
  saleOption: null,
  unitTypes: null,
  locationGovernorate: "",
  locationRegion: "",
  priceFrom: 0,
  priceTo: 0,
  numBathrooms: 0,
  numBedrooms: 0,
  areaFrom: 0,
  areaTo: 0,
  finishedOption: null,
  paymentType: "",
  sort: null,
  propFinancing: "",
  searchKeyword: "",
  openFilter: true,
  clickOnUnits: false,
  // sending: false,
  // filterResult: null,
  // errorResult: null,
  // queryInput: {},
  // pagesInput: {},
  // openSaveFilterInput: "",
  // confirmSendMessage: "",
  // isSaveed: "",
  // sortKey: "",
  // paymentTypeKey: "",
  // finishedOptionKey: "",
  // unitTypesKey: "",
  // saleOptionKey: "",
  // categoryTypeKey: "",
};
