export const initialStateCategory = {
  searchData: null,
  pageNumber: 0,
  categoryType: null,
  saleOption: null,
  unitTypes: null,
  locationGovernorate: "",
  locationRegion: "",
  priceFrom: 0,
  priceTo: 0,
  numBathrooms: 0,
  numBedrooms: 0,
  areaFrom: 0,
  areaTo: 0,
  finishedOption: null,
  paymentType: "",
  sort: null,
  propFinancing: "",
  searchKeyword: "",
  openFilter: false,
  clickOnUnits: false,
  // sending: false,
  // filterResult: null,
  // errorResult: null,
  // queryInput: {},
  // pagesInput: {},
  confirmSendMessage: false,
  messageData: "",
  isSaved: false,
  // sortKey: "",
  // paymentTypeKey: "",
  // finishedOptionKey: "",
  // unitTypesKey: "",
  // saleOptionKey: "",
  // categoryTypeKey: "",
};
