export const initialStateCategory = {
  pageNumber: 1,
  categoryType: "",
  saleOption: "",
  unitTypes: "",
  locationGovernorate: "",
  locationRegion: "",
  priceFrom: 0,
  priceTo: 0,
  numBathrooms: 0,
  numBedrooms: 0,
  areaFrom: 0,
  areaTo: 0,
  finishedOption: "",
  paymentType: "",
  sort: "",
  propFinancing: "",
  searchKeyword: "",
  openFilter: false,
  clickOnUnits: false,
  sending: false,
  filterResult: null,
  errorResult: null,
  // queryInput: {},
  // pagesInput: {},
  // openSaveFilterInput: "",
  // confirmSendMessage: "",
  // isSaveed: "",
  // sortKey: "",
  // paymentTypeKey: "",
  // finishedOptionKey: "",
  // unitTypesKey: "",
  // saleOptionKey: "",
  // categoryTypeKey: "",
};
